INSERT into cliente(cliente, endereco, cidade, cep, uf, cgc, estado) values('Álvaro Dias', 'Rua das Ladeiras nº12', 'Bento Gonçalves', '14252315', 'PR', '12365478/7894-7', '1365');
INSERT into cliente(cliente, endereco, cidade, cep, uf, cgc, estado) values('Joanadarque de Albuquerque', 'Rua 25 nº15', 'Almeida', '87459632', 'RJ', '14785236/8745-9', '4569');
INSERT into cliente(cliente, endereco, cidade, cep, uf, cgc, estado) values('Paulo José', 'Rua Teves Moreira nº256', 'São Bento', '14987365', 'PR', '13654478/7894-9', '1365');
INSERT into cliente(cliente, endereco, cidade, cep, uf, cgc, estado) values('José de Arimatéia', 'Rua Chico Xavier', 'Rio de Janeiro', '16478896', 'RJ', '15975313/4563-4', '1378');
INSERT into cliente(cliente, endereco, cidade, cep, uf, cgc, estado) values('Joe Peterson', 'Rua Valão do Sul nº12', 'São Luis', '65000000', 'MA', '1236545/4569-7', '4468');
INSERT into cliente(cliente, endereco, cidade, cep, uf, cgc, estado) values('Célia', 'Av. Peres Santos nº123', 'Niterói', '30042345', 'RJ', '7894569/7894-1', '1235');
INSERT into cliente(cliente, endereco, cidade, cep, uf, cgc, estado) values('Weslley Silva Swesgni', 'Rua Mailto nº123', 'Pacaembu', '23581236', 'SP', '13634569/7894-5', '4651');
INSERT into cliente(cliente, endereco, cidade, cep, uf, cgc, estado) values('Eduardo Andrade', 'Rua 13, nº25', 'Baixada', '12456369', 'RJ', '12345698/4789-1', '4651');
INSERT into cliente(cliente, endereco, cidade, cep, uf, cgc, estado) values('Robson Aquino Rêgo', 'Rua Maceió nº13', 'Mato Velho', '14781236', 'MG', '45678912/1234-1', '1234');
INSERT into cliente(cliente, endereco, cidade, cep, uf, cgc, estado) values('Paula', 'Av. Taqueino Vento nº24', 'Mafus', '65897423', 'DF', '45677894/7894-7', '4565');
INSERT into cliente(cliente, endereco, cidade, cep, uf, cgc, estado) values('Jó Santos', 'Av. Tapueba nº15', 'Ibiraquera', '14875789', 'SP', '78955462', '52314698/7531-8', '4567');
INSERT into cliente(cliente, endereco, cidade, cep, uf, cgc, estado) values('Lucio', 'Rua 15', 'São Luis', '65000000', 'MA', '12354598/123', '1452');
INSERT into cliente(cliente, endereco, cidade, cep, uf, cgc, estado) values('Julio Batista', 'Rua Dep Fernando Henrique nº57', 'São Luis', '65000000', 'MA', '45688965/7894-6', '4561');
INSERT into cliente(cliente, endereco, cidade, cep, uf, cgc, estado) values('Maria', 'Rua Lopes nº21', 'Curitiba', '30078500', 'PR', '12365445/1452-1', '4561');﻿